// Industry benchmarks and application constants
export const INDUSTRY_BENCHMARKS = {
  SAFARI_TRAFFIC_AVERAGE: 35,
  UNAUTHENTICATED_USERS: 70,
  TYPICAL_MATCH_RATE: 45,
  AVERAGE_YIELD_UPLIFT: 25,
  US_CHROME_MARKET_SHARE: 50.63,
  PAGES_PER_SESSION: 2.5,
  CPM_IMPROVEMENT_FACTOR: 1.25,
  ID_BLOAT_REDUCTION_PERCENTAGE: 20,
  COST_PER_ID_REDUCTION: 0.004,
} as const;

export const DEFAULT_CALCULATOR_VALUES = {
  MONTHLY_PAGEVIEWS: 5000000,
  AD_IMPRESSIONS_PER_PAGE: 3.2,
  WEB_DISPLAY_CPM: 4.50,
  WEB_VIDEO_CPM: 12.00,
  DISPLAY_VIDEO_SPLIT: 80,
  NUM_DOMAINS: 1,
} as const;

export const DEFAULT_SALES_MIX = {
  direct: 40,
  dealIds: 35,
  openExchange: 25,
} as const;

export const GRADE_THRESHOLDS = {
  A_PLUS: 3.8,
  A: 3.5,
  B: 3.0,
  C: 2.5,
  D: 2.0,
} as const;

export const ID_MULTIPLICATION_FACTORS = {
  ADDITIONAL_DOMAIN_FACTOR: 0.3,
  BROWSER_FRAGMENTATION_FACTOR: 0.4,
  SALES_COMPLEXITY_FACTOR: 0.2,
} as const;

export const RAMP_UP_SCHEDULE = {
  MONTH_1_FACTOR: 0.15,
  MONTH_2_FACTOR: 0.35,
  MONTH_3_PLUS_FACTOR: 1.0,
} as const;